# データサンプル生成 Case2-販売データ

## インスタンス宣言とLocale

In [5]:
import pandas as pd
from faker import Faker

fake_ja = Faker("ja_JP")
fake_ja.seed_instance(42)

In [6]:
import random
import pandas as pd
from datetime import date
from faker import Faker

fake_orders = Faker("ja_JP")
fake_orders.seed_instance(27)

rng = random.Random(27)

In [7]:
customers = []

for i in range(1, 11):
    customers.append({
        "customer_id": f"C{i:04d}",
        "name": fake_ja.unique.name(),
        "email": fake_ja.unique.safe_email(),
        "phone": fake_ja.unique.phone_number(),
        "address": fake_ja.unique.address().replace("\n", " "),
        "registered_at": fake_ja.date_between(
            start_date="-1y",
            end_date="today"
        )
    })

customers_df = pd.DataFrame(customers)

display(customers_df)

,customer_id,name,email,phone,address,registered_at
0,C0001,佐藤 淳,tomoyatakahashi@example.org,070-9600-1338,青森県小平市上吉羽42丁目23番18号 シティ神明内940,2026-07-19
1,C0002,橋本 太一,sotaro35@example.org,070-6155-9407,茨城県川崎市川崎区港南6丁目18番10号 パーク上高野034,2026-10-10
2,C0003,遠藤 拓真,rei52@example.com,090-3419-2832,滋賀県長生郡長南町神明内21丁目27番2号 千塚パレス641,2025-12-31
3,C0004,田中 幹,psaito@example.com,080-4238-8496,京都府品川区神明内9丁目17番16号 ハイツ中三依226,2026-05-21
4,C0005,小林 美加子,sayuri01@example.net,090-5146-2704,千葉県三鷹市美原町41丁目10番17号 アーバン渡辺288,2026-09-16
5,C0006,佐々木 加奈,manabu30@example.org,070-1718-2278,石川県昭島市箪笥町14丁目18番7号,2026-07-02
6,C0007,中川 里佳,ryohei87@example.org,080-3150-9839,北海道八街市日光15丁目3番2号,2026-08-25
7,C0008,山口 淳,iito@example.net,37-6311-6566,沖縄県浦安市南赤田4丁目13番11号 美原町アーバン387,2025-12-05
8,C0009,渡辺 翔太,yoshidasayuri@example.org,070-8013-2677,京都府横浜市泉区日光11丁目13番1号,2026-10-10
9,C0010,西村 美加子,ryosuke87@example.org,080-4309-8050,愛媛県八王子市西浅草34丁目6番2号,2026-10-01

In [8]:
products = [
    {"name": "ノートPC", "price": 120000},
    {"name": "マウス", "price": 3000},
    {"name": "キーボード", "price": 8000},
    {"name": "モニター", "price": 35000},
    {"name": "USBハブ", "price": 2500},
]

orders = []
customers = customers_df.to_dict("records")

for i in range(1, 51):
    customer = rng.choice(customers)
    product = rng.choice(products)
    quantity = rng.randint(1, 3)

    orders.append({
        "order_id": f"O{i:05d}",
        "customer_id": customer["customer_id"],
        "order_date": fake_orders.date_between_dates(
            date_start=customer["registered_at"],
            date_end=date.today()
        ),
        "product_name": product["name"],
        "quantity": quantity,
        "unit_price": product["price"],
        "total_amount": product["price"] * quantity
    })

orders_df = pd.DataFrame(orders)

display(orders_df)

,order_id,customer_id,order_date,product_name,quantity,unit_price,total_amount
0,O00001,C0008,2026-06-27,キーボード,2,8000,16000
1,O00002,C0004,2026-09-01,ノートPC,1,120000,120000
2,O00003,C0005,2026-10-14,USBハブ,2,2500,5000
3,O00004,C0005,2026-09-21,キーボード,2,8000,16000
4,O00005,C0003,2026-01-18,マウス,1,3000,3000
5,O00006,C0008,2026-08-21,ノートPC,3,120000,360000
6,O00007,C0010,2026-10-05,ノートPC,3,120000,360000
7,O00008,C0007,2026-09-13,モニター,3,35000,105000
8,O00009,C0001,2026-09-29,モニター,2,35000,70000
9,O00010,C0001,2026-08-04,モニター,2,35000,70000
10,O00011,C0003,2026-09-19,USBハブ,2,2500,5000
11,O00012,C0010,2026-10-08,マウス,3,3000,9000
12,O00013,C0009,2026-10-10,マウス,1,3000,3000
13,O00014,C0007,2026-10-11,キーボード,3,8000,24000
14,O00015,C0001,2026-09-07,USBハブ,1,2500,2500
15,O00016,C0003,2026-01-22,モニター,3,35000,105000
16,O00017,C0003,2026-08-30,キーボード,3,8000,24000
17,O00018,C0001,2026-09-25,マウス,3,3000,9000
18,O00019,C0001,2026-09-22,モニター,1,35000,35000
19,O00020,C0006,2026-09-09,USBハブ,3,2500,7500
20,O00021,C0007,2026-10-15,ノートPC,2,120000,240000
21,O00022,C0008,2025-12-08,モニター,2,35000,70000
22,O00023,C0001,2026-10-13,キーボード,1,8000,8000
23,O00024,C0005,2026-10-05,マウス,2,3000,6000
24,O00025,C0006,2026-07-28,USBハブ,1,2500,2500
25,O00026,C0009,2026-10-13,マウス,1,3000,3000
26,O00027,C0004,2026-07-09,モニター,3,35000,105000
27,O00028,C0002,2026-10-13,キーボード,2,8000,16000
28,O00029,C0001,2026-09-19,モニター,2,35000,70000
29,O00030,C0002,2026-10-13,キーボード,2,8000,16000
30,O00031,C0009,2026-10-10,ノートPC,2,120000,240000
31,O00032,C0008,2026-04-07,モニター,2,35000,70000
32,O00033,C0009,2026-10-11,ノートPC,3,120000,360000
33,O00034,C0001,2026-09-23,キーボード,1,8000,8000
34,O00035,C0008,2026-09-24,USBハブ,3,2500,7500
35,O00036,C0002,2026-10-14,ノートPC,3,120000,360000
36,O00037,C0001,2026-09-04,キーボード,1,8000,8000
37,O00038,C0005,2026-09-21,USBハブ,1,2500,2500
38,O00039,C0001,2026-09-19,USBハブ,2,2500,5000
39,O00040,C0007,2026-09-07,モニター,3,35000,105000
40,O00041,C0001,2026-10-15,マウス,2,3000,6000
41,O00042,C0001,2026-08-03,USBハブ,1,2500,2500
42,O00043,C0004,2026-10-11,モニター,1,35000,35000
43,O00044,C0006,2026-07-03,モニター,1,35000,35000
44,O00045,C0006,2026-09-22,ノートPC,1,120000,120000
45,O00046,C0002,2026-10-12,ノートPC,2,120000,240000
46,O00047,C0004,2026-08-13,マウス,2,3000,6000
47,O00048,C0010,2026-10-07,モニター,1,35000,35000
48,O00049,C0004,2026-07-05,USBハブ,2,2500,5000
49,O00050,C0005,2026-09-29,ノートPC,3,120000,360000